INSERT INTO cid (code, cid, classification, description)
VALUES ("A000", "CID10", "Cólera", "Cólera devida a Vibrio cholerae 01, biótipo cholerae"),
	   ("A001", "CID10", "Cólera", "Cólera devida a Vibrio cholerae 01, biótipo El Tor"),
	   ("A009", "CID10", "Cólera", "Cólera não especificada"),
	   ("A01", "CID10", "Febres Tifóide e Paratifóide", "Febres Tifóide"),
	   ("A02", "CID10", "Outras Infecções Por Salmonella", "Outras Infecções Por Salmonella"),
	   ("A03", "CID10", "Shiguelose", "Shiguelose"),
	   ("A04", "CID10", "Outras infecções intestinais bacterianas", "Outras infecções intestinais bacterianas"),
	   ("A05", "CID10", "Outras intoxicações alimentares bacterianas, não classificadas em outra parte", "Outras intoxicações alimentares bacterianas, não classificadas em outra parte"),
	   ("A31", "CID10", "Infecções devidas a outras micobactérias", "Infecções devidas a outras micobactérias"),
	   ("A34", "CID10", "Tétano obstétrico", "Tétano obstétricoTétano obstétrico"),
	   ("A49", "CID10", "Infecção bacteriana de localização não especificada", "Infecção bacteriana de localização não especificada"),
	   ("B05", "CID10", "Sarampo", "Sarampo"),
	   ("B06", "CID10", "Rubéola", "Rubéola"),
	   ("B08", "CID10", "Outras infecções virais caracterizadas por lesões da pele e das membranas mucosas, não classificadas em outra parte", "Outras infecções virais caracterizadas por lesões da pele e das membranas mucosas, não classificadas em outra parte"),
	   ("B37", "CID10", "Candidíase", "Candidíase"),
	   ("C00", "CID10", "Neoplasia maligna do lábio", "Neoplasia maligna do lábio"),
	   ("C15", "CID10", "Neoplasia maligna do esôfago", "Neoplasia maligna do esôfago"),
	   ("C17", "CID10", "Neoplasia maligna do intestino delgado", "Neoplasia maligna do intestino delgado"),
	   ("I05", "CID10", "Doenças reumáticas crônicas do coração", "Doenças reumáticas da valva mitral"),
	   ("I06", "CID10", "Doenças reumáticas crônicas do coração", "Doenças reumáticas da valva aórtica"),
	   ("I09", "CID10", "Doenças reumáticas crônicas do coração", "Outras doenças reumáticas do coração"),
	   ("F00", "CID10", "Transtornos mentais e comportamentais ", "Demência na doença de Alzheimer"),
	   ("F06", "CID10", "Transtornos mentais e comportamentais ", "Outros transtornos mentais devidos a lesão e disfunção cerebral e a doença física"),
	   ("F05", "CID10", "Transtornos mentais e comportamentais ", "Delirium não induzido pelo álcool ou por outras substâncias psicoativas"),
	   ("F99", "CID10", "Transtornos mentais e comportamentais ", "Transtorno mental não especificado em outra parte"),
	   ("V01", "CID10", "Acidentes", "Pedestre traumatizado em colisão com um veículo a pedal"),
	   ("V06", "CID10", "Acidentes", "Pedestre traumatizado em colisão com outro veículo não-motorizado"),
	   ("W03", "CID10", "Acidentes", "Outras quedas no mesmo nível por colisão com ou empurrão por outra pessoa"),
	   ("W32", "CID10", "Acidentes", "Projétil de revólver"),
	   ("U049", "CID10", "Designação provisória de novas doenças de etiologia incerta", "Síndrome respiratória aguda grave [severe acute respiratory syndrome SARS]"),
	   ("U88", "CID10", "Agentes bacterianos resistentes a antibióticos", "Agente resistente a múltiplos antibióticos"),
	   ("Z20", "CID10", "Contato com e exposição a doenças transmissíveis", "Contato com e exposição a doenças transmissíveis");	   